### ISSUE TITLE
Config import error "Call to a member function getSettings() on null"

### ISSUE THREAD

**Issue by leeomara** [ytgov/yukon-ca#537]
Another in the line of #481 and #483. 

Running `drush config:import` on a freshly installed site fails (after seeing "TypeError on ReverseContainer::generateServiceIdHash", see #483) with

```
 [error]  Error: Call to a member function getSettings() on null in Drupal\Core\Field\FieldConfigBase->getSettings() (line 375 of /var/www/yukon-ca-d10/docroot/core/lib/Drupal/Core/Field/FieldConfigBase.php) #0 /var/www/yukon-ca-d10/docroot/core/lib/Drupal/Core/Field/FieldConfigBase.php(289): Drupal\Core\Field\FieldConfigBase->getSettings()
#1 /var/www/yukon-ca-d10/docroot/core/lib/Drupal/Core/Config/Entity/ConfigEntityStorage.php(430): Drupal\Core\Field\FieldConfigBase->postCreate()
#2 /var/www/yukon-ca-d10/docroot/core/lib/Drupal/Core/Config/Entity/ConfigEntityStorage.php(357): Drupal\Core\Config\Entity\ConfigEntityStorage->_doCreateFromStorageRecord()
#3 /var/www/yukon-ca-d10/docroot/core/lib/Drupal/Core/Config/ConfigImporter.php(1068): Drupal\Core\Config\Entity\ConfigEntityStorage->importCreate()
#4 /var/www/yukon-ca-d10/docroot/core/lib/Drupal/Core/Config/ConfigImporter.php(851): Drupal\Core\Config\ConfigImporter->importInvokeOwner()
#5 /var/www/yukon-ca-d10/docroot/core/lib/Drupal/Core/Config/ConfigImporter.php(672): Drupal\Core\Config\ConfigImporter->processConfiguration()
#6 /var/www/yukon-ca-d10/docroot/core/lib/Drupal/Core/Config/ConfigImporter.php(570): Drupal\Core\Config\ConfigImporter->processConfigurations()
#7 /var/www/yukon-ca-d10/vendor/drush/drush/src/Commands/config/ConfigImportCommands.php(259): Drupal\Core\Config\ConfigImporter->doSyncStep()
#8 /var/www/yukon-ca-d10/vendor/drush/drush/includes/drush.inc(62): Drush\Commands\config\ConfigImportCommands->doImport()
#9 /var/www/yukon-ca-d10/vendor/drush/drush/includes/drush.inc(53): drush_call_user_func_array()
#10 /var/www/yukon-ca-d10/vendor/drush/drush/src/Commands/config/ConfigImportCommands.php(230): drush_op()
#11 [internal function]: Drush\Commands\config\ConfigImportCommands->import()
#12 /var/www/yukon-ca-d10/vendor/consolidation/annotated-command/src/CommandProcessor.php(276): call_user_func_array()
#13 /var/www/yukon-ca-d10/vendor/consolidation/annotated-command/src/CommandProcessor.php(212): Consolidation\AnnotatedCommand\CommandProcessor->runCommandCallback()
#14 /var/www/yukon-ca-d10/vendor/consolidation/annotated-command/src/CommandProcessor.php(176): Consolidation\AnnotatedCommand\CommandProcessor->validateRunAndAlter()
#15 /var/www/yukon-ca-d10/vendor/consolidation/annotated-command/src/AnnotatedCommand.php(391): Consolidation\AnnotatedCommand\CommandProcessor->process()
#16 /var/www/yukon-ca-d10/vendor/symfony/console/Command/Command.php(326): Consolidation\AnnotatedCommand\AnnotatedCommand->execute()
#17 /var/www/yukon-ca-d10/vendor/symfony/console/Application.php(1096): Symfony\Component\Console\Command\Command->run()
#18 /var/www/yukon-ca-d10/vendor/symfony/console/Application.php(324): Symfony\Component\Console\Application->doRunCommand()
#19 /var/www/yukon-ca-d10/vendor/symfony/console/Application.php(175): Symfony\Component\Console\Application->doRun()
#20 /var/www/yukon-ca-d10/vendor/drush/drush/src/Runtime/Runtime.php(110): Symfony\Component\Console\Application->run()
#21 /var/www/yukon-ca-d10/vendor/drush/drush/src/Runtime/Runtime.php(40): Drush\Runtime\Runtime->doRun()
#22 /var/www/yukon-ca-d10/vendor/drush/drush/drush.php(139): Drush\Runtime\Runtime->run()
#23 /var/www/yukon-ca-d10/vendor/drush/drush/drush(4): require('...')
#24 /var/www/yukon-ca-d10/vendor/bin/drush(119): include('...')
#25 {main}. 
```

Patching `core/lib/Drupal/Core/Field/FieldConfigBase.php` with 

```diff
diff --git a/core/lib/Drupal/Core/Field/FieldConfigBase.php b/core/lib/Drupal/Core/Field/FieldConfigBase.php
--- a/core/lib/Drupal/Core/Field/FieldConfigBase.php	
+++ b/core/lib/Drupal/Core/Field/FieldConfigBase.php	
@@ -369,6 +369,11 @@
    * {@inheritdoc}
    */
   public function getSettings() {
+    if ($this->getFieldStorageDefinition() === NULL) {
+      $e = new \Exception();
+      \Drupal::logger(__CLASS__)->error('Fetching field storage definitions could not be fetched for "%name". Stack trace: <pre>%debug</pre>', ['%name' => $this->getName() , '%debug' => $e->getTraceAsString()]);
+      return $this->settings;
+    }
     return $this->settings + $this->getFieldStorageDefinition()->getSettings();
   }
 ```

From https://www.drupal.org/project/drupal/issues/3441962#comment-15646229

Allows the import to complete. It reports a number of exceptions starting with

> Fetching field storage definitions could not be fetched for "moderation_state"

```
 [error]  Fetching field storage definitions could not be fetched for "moderation_state". Stack trace: <pre>#0 /var/www/yukon-ca-d10/docroot/core/lib/Drupal/Core/Field/FieldConfigBase.php(289): Drupal\Core\Field\FieldConfigBase->getSettings()
#1 /var/www/yukon-ca-d10/docroot/core/lib/Drupal/Core/Config/Entity/ConfigEntityStorage.php(430): Drupal\Core\Field\FieldConfigBase->postCreate()
#2 /var/www/yukon-ca-d10/docroot/core/lib/Drupal/Core/Config/Entity/ConfigEntityStorage.php(357): Drupal\Core\Config\Entity\ConfigEntityStorage->_doCreateFromStorageRecord()
#3 /var/www/yukon-ca-d10/docroot/core/lib/Drupal/Core/Config/ConfigImporter.php(1068): Drupal\Core\Config\Entity\ConfigEntityStorage->importCreate()
#4 /var/www/yukon-ca-d10/docroot/core/lib/Drupal/Core/Config/ConfigImporter.php(851): Drupal\Core\Config\ConfigImporter->importInvokeOwner()
#5 /var/www/yukon-ca-d10/docroot/core/lib/Drupal/Core/Config/ConfigImporter.php(672): Drupal\Core\Config\ConfigImporter->processConfiguration()
#6 /var/www/yukon-ca-d10/docroot/core/lib/Drupal/Core/Config/ConfigImporter.php(570): Drupal\Core\Config\ConfigImporter->processConfigurations()
#7 /var/www/yukon-ca-d10/vendor/drush/drush/src/Commands/config/ConfigImportCommands.php(259): Drupal\Core\Config\ConfigImporter->doSyncStep()
#8 /var/www/yukon-ca-d10/vendor/drush/drush/includes/drush.inc(62): Drush\Commands\config\ConfigImportCommands->doImport()
#9 /var/www/yukon-ca-d10/vendor/drush/drush/includes/drush.inc(53): drush_call_user_func_array()
#10 /var/www/yukon-ca-d10/vendor/drush/drush/src/Commands/config/ConfigImportCommands.php(230): drush_op()
#11 [internal function]: Drush\Commands\config\ConfigImportCommands->import()
#12 /var/www/yukon-ca-d10/vendor/consolidation/annotated-command/src/CommandProcessor.php(276): call_user_func_array()
#13 /var/www/yukon-ca-d10/vendor/consolidation/annotated-command/src/CommandProcessor.php(212): Consolidation\AnnotatedCommand\CommandProcessor->runCommandCallback()
#14 /var/www/yukon-ca-d10/vendor/consolidation/annotated-command/src/CommandProcessor.php(176): Consolidation\AnnotatedCommand\CommandProcessor->validateRunAndAlter()
#15 /var/www/yukon-ca-d10/vendor/consolidation/annotated-command/src/AnnotatedCommand.php(391): Consolidation\AnnotatedCommand\CommandProcessor->process()
#16 /var/www/yukon-ca-d10/vendor/symfony/console/Command/Command.php(326): Consolidation\AnnotatedCommand\AnnotatedCommand->execute()
#17 /var/www/yukon-ca-d10/vendor/symfony/console/Application.php(1096): Symfony\Component\Console\Command\Command->run()
#18 /var/www/yukon-ca-d10/vendor/symfony/console/Application.php(324): Symfony\Component\Console\Application->doRunCommand()
#19 /var/www/yukon-ca-d10/vendor/symfony/console/Application.php(175): Symfony\Component\Console\Application->doRun()
#20 /var/www/yukon-ca-d10/vendor/drush/drush/src/Runtime/Runtime.php(110): Symfony\Component\Console\Application->run()
#21 /var/www/yukon-ca-d10/vendor/drush/drush/src/Runtime/Runtime.php(40): Drush\Runtime\Runtime->doRun()
#22 /var/www/yukon-ca-d10/vendor/drush/drush/drush.php(139): Drush\Runtime\Runtime->run()
#23 /var/www/yukon-ca-d10/vendor/drush/drush/drush(4): require('...')
#24 /var/www/yukon-ca-d10/vendor/bin/drush(119): include('...')
#25 {main}</pre> 
```

**Comment by w3creatives** [comment]
We have added patch for that. Please test again and let us know.

**Comment by leeomara** [comment]
This was not a problem when we last rebuilt the site on dev or UAT.
