### ISSUE TITLE
Initial migration fails with error "getUrl() on null"

### ISSUE THREAD

**Issue by leeomara** [ytgov/yukon-ca#546]
When working on a fresh install, the initial migration fails with this error:

> Call to a member function getUrl() on null in /var/www/yukon-ca-d10/docroot/core/modules/menu_link_content/src/Entity/MenuLinkContent.php on line 95

The full trace is:
```
Error: Call to a member function getUrl() on null in docroot/core/modules/menu_link_content/src/Entity/MenuLinkContent.php on line 95 #0 docroot/core/modules/menu_link_content/src/Entity/MenuLinkContent.php(157): Drupal\menu_link_content\Entity\MenuLinkContent->getUrlObject()
#1 docroot/core/modules/menu_link_content/src/Entity/MenuLinkContent.php(223): Drupal\menu_link_content\Entity\MenuLinkContent->getPluginDefinition()
#2 docroot/core/lib/Drupal/Core/Entity/EntityStorageBase.php(563): Drupal\menu_link_content\Entity\MenuLinkContent->postSave()
#3 docroot/core/lib/Drupal/Core/Entity/ContentEntityStorageBase.php(781): Drupal\Core\Entity\EntityStorageBase->doPostSave()
#4 docroot/core/lib/Drupal/Core/Entity/EntityStorageBase.php(489): Drupal\Core\Entity\ContentEntityStorageBase->doPostSave()
#5 docroot/core/lib/Drupal/Core/Entity/Sql/SqlContentEntityStorage.php(806): Drupal\Core\Entity\EntityStorageBase->save()
#6 docroot/core/lib/Drupal/Core/Entity/EntityBase.php(354): Drupal\Core\Entity\Sql\SqlContentEntityStorage->save()
#7 docroot/core/modules/migrate/src/Plugin/migrate/destination/EntityContentBase.php(237): Drupal\Core\Entity\EntityBase->save()
#8 docroot/core/modules/migrate/src/Plugin/migrate/destination/EntityContentBase.php(175): Drupal\migrate\Plugin\migrate\destination\EntityContentBase->save()
#9 docroot/core/modules/migrate/src/MigrateExecutable.php(248): Drupal\migrate\Plugin\migrate\destination\EntityContentBase->import()
#10 vendor/drush/drush/includes/drush.inc(62): Drupal\migrate\MigrateExecutable->import()
#11 vendor/drush/drush/includes/drush.inc(53): drush_call_user_func_array()
#12 docroot/modules/contrib/migrate_tools/src/Drush/Commands/MigrateToolsCommands.php(1072): drush_op()
#13 docroot/modules/contrib/migrate_tools/src/Drush/Commands/MigrateToolsCommands.php(483): Drupal\migrate_tools\Drush\Commands\MigrateToolsCommands->executeMigration()
#14 [internal function]: Drupal\migrate_tools\Drush\Commands\MigrateToolsCommands->import()
#15 vendor/consolidation/annotated-command/src/CommandProcessor.php(276): call_user_func_array()
#16 vendor/consolidation/annotated-command/src/CommandProcessor.php(212): Consolidation\AnnotatedCommand\CommandProcessor->runCommandCallback()
#17 vendor/consolidation/annotated-command/src/CommandProcessor.php(176): Consolidation\AnnotatedCommand\CommandProcessor->validateRunAndAlter()
#18 vendor/consolidation/annotated-command/src/AnnotatedCommand.php(391): Consolidation\AnnotatedCommand\CommandProcessor->process()
#19 vendor/symfony/console/Command/Command.php(326): Consolidation\AnnotatedCommand\AnnotatedCommand->execute()
#20 vendor/symfony/console/Application.php(1096): Symfony\Component\Console\Command\Command->run()
#21 vendor/symfony/console/Application.php(324): Symfony\Component\Console\Application->doRunCommand()
#22 vendor/symfony/console/Application.php(175): Symfony\Component\Console\Application->doRun()
#23 vendor/drush/drush/src/Runtime/Runtime.php(110): Symfony\Component\Console\Application->run()
#24 vendor/drush/drush/src/Runtime/Runtime.php(40): Drush\Runtime\Runtime->doRun()
#25 vendor/drush/drush/drush.php(139): Drush\Runtime\Runtime->run()
#26 vendor/drush/drush/drush(4): require('...')
#27 vendor/bin/drush(119): include('...')
#28 {main}
```

# Steps to reproduce

run `migrate_initial.sh`, or `drush migrate:import yukon_migrate_menu_links_translation`

Though the script includes `--continue-on-failure`, this error causes the migration to stop.

**Comment by leeomara** [comment]
@w3creatives I believe you've already run into this issue, or was it something different?

**Comment by leeomara** [comment]
When running drush with `--debug`, this "info" message is reported before the error:

```
[info] parse_url(): Passing null to parameter #1 ($url) of type string is deprecated MenuLinkContent.php:199 [17.17 sec, 55.83 MB]
```

**Comment by w3creatives** [comment]
Which branch did you use to create a new installation?

**Comment by leeomara** [comment]
This was on `master`, either cb497b63 or the one before it

**Comment by leeomara** [comment]
When I tried after (locally) merging in `w3_staging_yukon`, this issue did not come up.

**Comment by w3creatives** [comment]
I just updated the w3_staging_yukon branch with latest updates.

**Comment by leeomara** [comment]
Migration ran on UAT without this error coming up.
